name: "🐛 Flow Bug Report"
description: "Quickly report a Flow bug (minimal form)"
labels: ["bug", "flow"]
title: "[Bug]: <short description>"

body:
  - type: textarea
    id: details
    attributes:
      label: "Bug Details"
      description: "Describe what went wrong, the expected behavior, and any relevant environment details (Flow & Bun version, DB, OS, etc.)."
      placeholder: |
        After running `bun flow enhance` I received ...
        Expected: ...
        Actual: ...
        Env: Flow 0.3.2, Bun 1.2.17, PostgreSQL 15 on Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce (optional)"
      description: "If applicable, list the minimal steps or SQL migration needed to reproduce the issue."
      placeholder: |
        1. Generate a migration ...
        2. Run `bun flow enhance` ...
    validations:
      required: false 