name: "✨ Flow Feature Request"
description: "Suggest an idea or improvement for Flow (short form)"
labels: ["enhancement", "flow"]
title: "[Feature]: <short description>"

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature"
      description: "What would you like Flow to do?"
      placeholder: |
        Add support for ...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: "Why is this useful? (optional)"
      description: "Explain the benefit or problem solved."
    validations:
      required: false 